### ISSUE TITLE
How to reset state?

### ISSUE THREAD

**Issue by AgustinPinedaGarcia** [vaibhavk97/Poe#1]
I'm having issues resetting the state of the chatbot (in case I'm interpreting it correctly). So, the command `!clear` is supposed to reset the conversation? If so, I'm still getting context from previous interactions (see the image; reference to Madrid even though I have reset the state). Why is this happening? How can I reset the current conversation and start over? 

![poe_reset_state](https://user-images.githubusercontent.com/102975601/221569280-098570bf-2d3b-4388-ad56-c84515d64fea.png)

**Comment by vaibhavk97** [comment]
Its fixed now, thanks for pointing out!
