### ISSUE TITLE
Integrating more features using GraphQL

### ISSUE THREAD

**Issue by vaibhavk97** [vaibhavk97/Poe#2]
The current version only works for basic actions required to chat with an LLM. However, there is additional possible functionality. GraphQL for Poe can be found here: https://github.com/ericlewis/poe-graphql/tree/main Can we possibly refactor the current code to better leverage the graphql based semantics?

**Comment by ading2210** [comment]
I've started work on a GraphQL-based Poe API wrapper here: https://github.com/ading2210/poe-api/

Currently there aren't a whole lot of features, but there's already support for streaming requests using websockets, and I've made it into a [PyPi package](https://pypi.org/project/poe-api/).
