### ISSUE TITLE
good stuff :)

### ISSUE THREAD

**Issue by xoiga123** [vaibhavk97/Poe#5]
i love you so much dude u don't even know :couplekiss:

**Comment by vaibhavk97** [comment]
Not something that I encountered, can you post the error, or is it just the http calls takes forever?

**Comment by xoiga123** [comment]
Yea at some point the bot decides to `response_json['data']['chatOfBot']['messagesConnection']['edges'][-1]['node']['state'] == "incomplete"` forever and Im stuck in a loop of 2s naps. I use `clear_context` after each call btw.

**Comment by xoiga123** [comment]
Yea anyway I modifed `get_latest_message` to be in a for-loop and returned `text = "God Machine said he didn't hear your prayer"` and when I call the function again, it returns the correct answer so all is good :sunglasses: idk why tho :sunglasses: ty

**Comment by vaibhavk97** [comment]
Glad its fine now!
