### ISSUE TITLE
Use with the new gpt3.5 chat?

### ISSUE THREAD

**Issue by User1231300** [vaibhavk97/Poe#6]
Could it be implemented?

**Comment by 7trail** [comment]
Hello,
I am not the creator of the repository, but I presume it to be possible, yes. If each model has an internal name (a2, capybara, nutria, etc) then any model SHOULD be accessible. Time to dig around for the names and submit a PR...

**Comment by ading2210** [comment]
My own Poe API wrapper should be able to access every chatbot that the site supports, including the ones based on `gpt-3.5-turbo`.

https://github.com/ading2210/poe-api
https://pypi.org/project/poe-api/

**Comment by vaibhavk97** [comment]
Yep, the newer bots are available and the names for the same can be found here: 

'capybara': 'Sage', 
'beaver': 'GPT-4', 
'a2_2': 'Claude+', 
'a2': 'Claude', 
'chinchilla': 'ChatGPT', 
'nutria': 'Dragonfly'
