### ISSUE TITLE
poe.com has new bot https://poe.com/NeevaAI

### ISSUE THREAD

**Issue by phamxtien** [vaibhavk97/Poe#9]

**Comment by phamxtien** [comment]
Wait for an update :)

**Comment by phamxtien** [comment]
Sage - OpenAI (capybara)
GPT-4 - OpenAI (beaver)
Claude+ - Anthropic (a2_2)
Claude - Anthropic (a2)
ChatGPT - OpenAI (chinchilla)
Dragonfly - OpenAI (nutria)

vs>> NeevaAI - (hutia)

**Comment by vaibhavk97** [comment]
Thats cool, please feel free to open a PR!

**Comment by phamxtien** [comment]
NeevaAI is off :)
